AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  albertchinesener:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: >-
        arn:aws:iam::847380964353:role/service-role/albert-chinese-ner-role-m3pz30qm
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /albert-chinese-ner
            Method: ANY
      Layers:
        - 'arn:aws:lambda:us-east-1:847380964353:layer:sagemaker:1'
